# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grasp < Formula
  desc "A password manager that does not require any type of storage."
  homepage "https://github.com/lucasepe/homebrew-grasp"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucasepe/grasp/releases/download/v0.3.0/grasp_0.3.0_darwin_arm64.tar.gz"
      sha256 "796e0d94f6156fe802f3c44dfa2294dd628723062734f2fcd0000eb79c358139"

      def install
        bin.install "grasp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasepe/grasp/releases/download/v0.3.0/grasp_0.3.0_darwin_amd64.tar.gz"
      sha256 "d052a7addf3d85dc9f22083b92ce944665dfe76f8937fc61d9f69bfa0374fe78"

      def install
        bin.install "grasp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasepe/grasp/releases/download/v0.3.0/grasp_0.3.0_linux_arm64.tar.gz"
      sha256 "cf087eb219d62bd21d62c78bbf3fae34c22882565bfda9c88dea6d7bf3593b80"

      def install
        bin.install "grasp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasepe/grasp/releases/download/v0.3.0/grasp_0.3.0_linux_amd64.tar.gz"
      sha256 "d7792b97b1ddf417659c1dc0c1252ce7de2de3b408f777519ac1703b8ec9f21c"

      def install
        bin.install "grasp"
      end
    end
  end
end
