# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grasp < Formula
  desc "A password manager that does not require any type of storage."
  homepage "https://github.com/lucasepe/homebrew-grasp"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucasepe/grasp/releases/download/v0.3.1/grasp_0.3.1_darwin_arm64.tar.gz"
      sha256 "c7ec0a1174bda13b77966096f6a250032199ec2cbadd7cc217e0a2b535270372"

      def install
        bin.install "grasp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasepe/grasp/releases/download/v0.3.1/grasp_0.3.1_darwin_amd64.tar.gz"
      sha256 "046812517f97cfb4b5180f157d66309613ae1dbd013e100787118f331562e4a2"

      def install
        bin.install "grasp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lucasepe/grasp/releases/download/v0.3.1/grasp_0.3.1_linux_amd64.tar.gz"
      sha256 "f242095411fbabac6bb18ab5838c92d2dca0bcef0225b7b3a370a6850b5381aa"

      def install
        bin.install "grasp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasepe/grasp/releases/download/v0.3.1/grasp_0.3.1_linux_arm64.tar.gz"
      sha256 "577187dd678173a901ac7e8d61ab258683a2b3b6bc34478e0de5ce7234dad1ac"

      def install
        bin.install "grasp"
      end
    end
  end
end
